config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'badges/index'
  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords' }
  root 'tests#index'

  resources :feedbacks, only: %i[new create]

  resources :tests, only: :index do
    member do
      post :begin
    end
  end

  resources :results, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :attempt
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, expect: :index
      end
      member do
        post :begin, to: 'tests#begin'
      end
    end
    resources :gists, only: %i[index destroy]
    resources :badges, shallow: true, expect: :index
  end

  resources :badges, only: :index
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord
  ATTEMPTS = ('1'..'10').freeze

  enum criteria: { category: 0, attempts: 1, named: 2, level: 3 }, _prefix: true

  has_many :earnings, dependent: :destroy
  has_many :users, through: :earnings

  validates :name, :filename, presence: true
  validates :criteria, uniqueness: { scope: :parameter }
end

app/controllers/admin/badges_controller.rb
# frozen_string_literal: true

class Admin::BadgesController < Admin::BaseController
  before_action :authenticate_user!
  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def create
    @badge_form = BadgeForm.new(badge_params)
    @badge = @badge_form.badge

    if @badge_form.save
      redirect_to admin_badge_path(@badge), notice: t('success', name: @badge.name)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy

    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :filename, :criteria, :parameter)
  end
end

app/controllers/badges_controller.rb
# frozen_string_literal: true

class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = Badge.all
  end
end

app/helpers/admin/badges_helper.rb
# frozen_string_literal: true

module Admin::BadgesHelper
  def all_images
    images = []
    images_all = Dir.entries('app/assets/images').select { |f| f =~ /.*(png)/ }
    (images_all).each_slice(1) { |tuple| images.push(tuple) }
    images
  end

  def categories_titles
    Category.all.collect { |c| [c.title, c.id] }
  end

  def tests_titles
    Test.all.collect { |t| [t.title, t.id] }
  end
end

app/helpers/badges_helper.rb
# frozen_string_literal: true

module BadgesHelper
  def human_enum_name(enum_name, enum_value)
    I18n.t("activerecord.attributes.badge.#{enum_name.to_s.pluralize}.#{enum_value}")
  end

  def parameter_name(badge)
    category_or_named?(badge) ? read_parameter_name(badge) : badge.parameter
  end

  private

  def read_parameter_name(badge)
    if badge.criteria_category?
      Category.find(badge.parameter).title
    else
      Test.find(badge.parameter).title
    end
  end

  def category_or_named?(badge)
    badge.criteria_category? || badge.criteria_named?
  end
end

app/views/admin/badges/_badge.html.erb
<tbody>
<tr>
  <td class="text-center"><%= badge.name %></td>
  <td class="text-center"><%= image_tag(badge.filename) %></td>
  <td class="text-center"><%= t("activerecord.attributes.badge.criteria.#{badge.criteria}") %></td>
  <td class="text-center"><%= parameter_name(badge) %></td>
  <td class="text-center"><%= link_to t('show'), admin_badge_path(badge) %></td>
  <td class="text-center"><%= link_to t('edit'), edit_admin_badge_path(badge) %></td>
  <td class="text-center"><%= link_to t('delete'), admin_badge_path(badge), method: :delete, data: { confirm: t('confirm', name: badge.name) } %></td>
</tr>
</tbody>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge] do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>
  </p>

  <p>
    <%= form.label :filename %>
    <%= form.collection_radio_buttons(:filename, all_images, :first, :last) do |b| %>
      <%= b.label { b.radio_button + image_tag(b.text) } %>
    <% end %>
  </p>

  <p>
    <%= form.label :criteria %>
    <%= form.select :criteria,
                    Badge.criteria.keys.collect{ |criteria| [human_enum_name(:criteria, criteria), criteria] },
                    prompt: t('prompt', name: t('activerecord.attributes.badge.criteria.one')) %>
  </p>

  <p>
    <%= form.label :parameter %><br>
    <%= form.select :parameter, categories_titles %><br>
  </p>

  <%= hidden_field_tag 'category_titles', categories_titles.to_json.html_safe %>
  <%= hidden_field_tag 'attempt_values', Badge::ATTEMPTS.to_a %>
  <%= hidden_field_tag 'test_titles', tests_titles.to_json.html_safe %>
  <%= hidden_field_tag 'test_levels', Test.levels.uniq %>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/admin/badges/edit.html.erb
<h1><%= t( 'change', name: t('activerecord.models.badge.one').downcase) %></h1>

<%= render 'form' %>

<p> <%= link_to t('back'), admin_badges_path %> </p>

app/views/admin/badges/index.html.erb
<h2><%= t('activerecord.models.badge.many') %></h2>

<p><%= link_to t('new', name: t('activerecord.models.badge.one')), new_admin_badge_path(@badge) %></p>

<table class="table table-striped">
  <thead>
  <tr class="table-info">
    <th class="text-center"><%= t('activerecord.attributes.badge.name')%></th>
    <th class="text-center"><%= t('activerecord.attributes.badge.filename')%></th>
    <th class="text-center"><%= t('activerecord.attributes.badge.criteria.one') %></th>
    <th class="text-center"><%= t('activerecord.attributes.badge.parameter') %></th>
    <th colspan="4" class="text-center"><%= t('actions') %></th>
  </tr>
  </thead>
  <%= render @badges %>

</table>

app/views/admin/badges/new.html.erb
<h1><%= t('new', name: t('activerecord.models.badge.one') ) %></h1>

<%= render 'form' %>

<%= link_to t('back'), admin_tests_path %>

app/views/admin/badges/show.html.erb
<h1><%= t('activerecord.models.badge.one') %></h1>

<p><%= t('activerecord.attributes.badge.name') %> <%= @badge.name %> </p>
<p><%= t('activerecord.attributes.badge.filename') %> <%= image_tag(@badge.filename) %> </p>
<p><%= t('activerecord.attributes.badge.criteria.one') %> <%= human_enum_name(:criteria, @badge.criteria) %> </p>
<p><%= t('activerecord.attributes.badge.parameter') %> <%= parameter_name(@badge) %> </p>

<p> <%= link_to t('back'), admin_badges_path %> </p>