config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'badges/index'
  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords' }
  root 'tests#index'

  resources :feedbacks, only: %i[new create]

  resources :tests, only: :index do
    member do
      post :begin
    end
  end

  resources :results, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :attempt
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, expect: :index
      end
      member do
        post :begin, to: 'tests#begin'
      end
    end
    resources :gists, only: %i[index destroy]
    resources :badges, shallow: true, expect: :index
  end

  resources :badges, only: :index
end

app/views/admin/_nav.html.erb
<div class="navbar navbar-warning bg-warning">
  <%= link_to t('.test_guru'), root_path, class: 'navbar-brand', data: {current_locale: I18n.locale } %>

  <span class="navbar-text">
    <% if user_signed_in? %>
      <%= change_locale %>
      <%= link_to t('activerecord.models.test.many'), admin_tests_path %>
      <%= link_to t('activerecord.models.gist.many'), admin_gists_path %>
      <%= link_to t('activerecord.models.badge.many'), admin_badges_path %>
      <%= t('.welcome')%>, <b><%= current_user.email %></b> <%= t('.guru')%> |
      <%= link_to t('.log_out'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('.log_in'), new_session_path(resource_name) %> |
      <%= link_to t('.sign_up'), new_registration_path(resource_name) %>
    <% end %>
  </span>
</div>