config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'badges/index'
  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords' }
  root 'tests#index'

  resources :feedbacks, only: %i[new create]

  resources :tests, only: :index do
    member do
      post :begin
    end
  end

  resources :results, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :attempt
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, expect: :index
      end
      member do
        post :begin, to: 'tests#begin'
      end
    end
    resources :gists, only: %i[index destroy]
    resources :badges, shallow: true, expect: :index
  end

  resources :badges, only: :index
end

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors' , data: { resource_id: resource.id } do %>
    <h2><%= t('.header', count: resource.errors.count) %></h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
  <% flash.each do |key, message| %>
    <div class="alert alert-warning" role="alert">
      <%= content_tag :p, message.html_safe, class: "flash#{key}" %>
    </div>
  <% end %>

app/views/shared/_footer.html.erb
<h5><%= t('.footer') %></h5>

<footer>
  <p><%= t('.current_year') %> <%= current_year %></p>
  <p><%= github_url('DaniyarKulmanov', 'TestGuru-') %></p>
  <p>Суть проекта создания ресурса для прохождения тестирования знаний программирования</p>
  <p><%= github_url('DaniyarKulmanov') %></p>
  <p><%= link_to 'Учебный проект в онлайн-школе Thinknetica', 'https://thinknetica.com/',target: '_blank' %></p>
  <p><%= link_to t('.feedback'), new_feedback_path %></p>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to t('.test_guru'), root_path, class: 'navbar-brand' %>

  <span class="navbar-text">
    <%= change_locale %>
    <% if current_user.is_a?(Admin) %>
      <%= link_to t('.admin_panel'), admin_tests_path %>
      <%= link_to t('activerecord.models.gist.many'), admin_gists_path %>
    <% end %>

    <% if user_signed_in? %>
      <%= link_to t('activerecord.models.badge.many'), badges_index_path %>
      <%= t('.welcome')%>, <b><%= current_user.email %></b> <%= t('.guru')%> |
      <%= link_to t('.log_out'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('.log_in'), new_session_path(resource_name) %> |
      <%= link_to t('.sign_up'), new_registration_path(resource_name) %>
    <% end %>
  </span>
</nav>

app/views/shared/_test_data.html.erb
<td class="text-center"><%= test.level %></td>
<td class="text-center"><%= test.questions.count %></td>
<td class="text-center"><%= test.category.title %></td>
<td class="text-center"><%= test.timer%></td>

app/views/shared/_test_header.html.erb
<th class="text-center"><%= t('activerecord.attributes.test.level')%></th>
<th class="text-center"><%= t('tests.index.question_count') %></th>
<th class="text-center"><%= t('activerecord.models.category.one') %></th>
<th class="text-center"><%= t('activerecord.attributes.test.timer') %></th>