config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'badges/index'
  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords' }
  root 'tests#index'

  resources :feedbacks, only: %i[new create]

  resources :tests, only: :index do
    member do
      post :begin
    end
  end

  resources :results, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :attempt
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, expect: :index
      end
      member do
        post :begin, to: 'tests#begin'
      end
    end
    resources :gists, only: %i[index destroy]
    resources :badges, shallow: true, expect: :index
  end

  resources :badges, only: :index
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/result.rb
# frozen_string_literal: true

class Result < ApplicationRecord
  SUCCESS_RATIO = 85
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  after_initialize

  before_validation :before_validation_set_first_question, on: :create

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    self.current_question = (timer_exceeded? ? nil : next_question)
    self.passed = score >= SUCCESS_RATIO && completed?
    save!
  end

  def completed?
    current_question.nil?
  end

  def score
    ((correct_questions.to_f / test.questions.count) * 100).round
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids&.map(&:to_i)&.sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def timer_exceeded?
    Time.zone.now >= created_at + test.timer * 60
  end
end

app/controllers/results_controller.rb
# frozen_string_literal: true

class ResultsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_result, only: %i[show attempt update gist]

  def show; end

  def attempt; end

  def update
    @result.accept!(params[:answer_ids])

    if @result.completed?
      TestsMailer.completed_test(@result).deliver_now
      BadgeDistribute.new(@result).call

      redirect_to attempt_result_path(@result)
    else
      render :show
    end
  end

  private

  def set_result
    @result = Result.find(params[:id])
  end
end

app/helpers/results_helper.rb
# frozen_string_literal: true

module ResultsHelper
  def attempt_information
    score = @result.score

    if @result.passed
      status = 'positive'
      result = t('results.passed', score: score)
    else
      status = 'negative'
      result = t('results.not_passed', score: score)
    end
    "<p span class=#{status}>#{result}</p>".html_safe
  end

  def correct_path(user)
    if user.is_a?(Admin)
      admin_tests_path
    else
      tests_path
    end
  end

  def progressbar_html
    content_tag(:div,
                content_tag(:div, nil,
                            class: 'progress-bar',
                            'aria-valuemax' => 100,
                            'aria-valuemin' => 0,
                            'aria-valuenow' => 0,
                            'role' => 'progressbar',
                            'style' => 'width: 0%',
                            data: { questions_max: @result.test.questions.length,
                                    current_question_number: @result.test.questions.find_index(@result.current_question) }),
                class: 'progress')
  end

  def timer_html
    content_tag(:div, nil,
                id: 'timer',
                data: { duration: @result.test.timer,
                        attempt_url: attempt_result_path(@result),
                        count_down_date: @result.created_at.utc.iso8601 })
  end
end

app/views/results/attempt.html.erb
<h1><%= t('.completed', title: @result.test.title) %></h1>

<%= t('.result_html', result: attempt_information ) %>

<p> <%= link_to t(:back), correct_path(@result.user) %> </p>

app/views/results/show.html.erb
<h1><%= t('.test', title: @result.test.title) %></h1>

<h3><%= t('activerecord.attributes.test.timer') %></h3>

<%= timer_html %>

<%= hidden_field_tag 'attempt_url', attempt_result_path(@result) %>

<p><%= t('.total.questions', count: @result.test.questions.count) %></p>

<p><%= t('.current_question', question_id: @result.current_question.id ) %></p>

<%= progressbar_html %>

<p>
  <b><%= @result.current_question.body %></b>
</p>

<p><%= t('.answers') %></p>

<%= form_with url: result_path(@result), id: 'result_test', method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @result.current_question.answers, :id, :body, include_hidden: false do |c| %>
    <p>
      <%= c.check_box id: "answer_ids#{c.object.id}"%>
      <%= c.label %>
    </p>
  <% end %>

  <p><%= link_to t('.gist_question'), result_gists_path(@result), method: :post %></p>
  <p> <%= form.submit t('.next') %></p>
<% end %>